// Otomatik üretilmiş ürün kataloğu (83 ürün)
const PRODUCTS = [
  {
    "id": 118,
    "sku": "YP-10351",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Samsung",
    "name": "Samsung Sepet Kasnağı",
    "image": "images/urunler/samsung-sepet-kasnagi.avif",
    "price": 429,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 119,
    "sku": "YP-10354",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Kapı Lastiği",
    "image": "images/urunler/vestel-kapi-lastigi.avif",
    "price": 1299,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 120,
    "sku": "YP-10357",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Elektronik Kart",
    "image": "images/urunler/bosch-elektronik-kart.avif",
    "price": 2159,
    "oldPrice": 2629,
    "stock": 3
  },
  {
    "id": 121,
    "sku": "YP-10360",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Su Seviye Sensörü",
    "image": "images/urunler/siemens-su-seviye-sensoru.avif",
    "price": 749,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 122,
    "sku": "YP-10363",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Program Saati",
    "image": "images/urunler/beko-program-saati.avif",
    "price": 1619,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 123,
    "sku": "YP-10366",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Rulman Seti",
    "image": "images/urunler/profilo-rulman-seti.avif",
    "price": 209,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 124,
    "sku": "YP-10369",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Keçe Seti",
    "image": "images/urunler/arcelik-kece-seti.avif",
    "price": 1079,
    "oldPrice": 1319,
    "stock": 23
  },
  {
    "id": 125,
    "sku": "YP-10372",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Samsung",
    "name": "Samsung Tahrik Kayışı",
    "image": "images/urunler/samsung-tahrik-kayisi.avif",
    "price": 1949,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 126,
    "sku": "YP-10375",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Pompa",
    "image": "images/urunler/vestel-pompa.avif",
    "price": 539,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 127,
    "sku": "YP-10378",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Motor",
    "image": "images/urunler/bosch-motor.avif",
    "price": 1409,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 128,
    "sku": "YP-10381",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Amortisör Takozu",
    "image": "images/urunler/siemens-amortisor-takozu.avif",
    "price": 2279,
    "oldPrice": 2779,
    "stock": 3
  },
  {
    "id": 129,
    "sku": "YP-10384",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Isıtıcı Rezistans",
    "image": "images/urunler/beko-isitici-rezistans.avif",
    "price": 869,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 130,
    "sku": "YP-10387",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Deterjan Haznesi",
    "image": "images/urunler/profilo-deterjan-haznesi.avif",
    "price": 1739,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 131,
    "sku": "YP-10390",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Kapı Kilidi",
    "image": "images/urunler/arcelik-kapi-kilidi.avif",
    "price": 329,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 132,
    "sku": "YP-10393",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Samsung",
    "name": "Samsung Basınç Şalteri",
    "image": "images/urunler/samsung-basinc-salteri.avif",
    "price": 1199,
    "oldPrice": 1459,
    "stock": 23
  },
  {
    "id": 133,
    "sku": "YP-10396",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Sepet Kasnağı",
    "image": "images/urunler/vestel-sepet-kasnagi.avif",
    "price": 2069,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 134,
    "sku": "YP-10399",
    "category": "camasir-makinesi",
    "categoryName": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Kapı Lastiği",
    "image": "images/urunler/bosch-kapi-lastigi.avif",
    "price": 659,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 135,
    "sku": "YP-10402",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Elektronik Kart",
    "image": "images/urunler/profilo-elektronik-kart.avif",
    "price": 379,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 136,
    "sku": "YP-10405",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Deterjan Haznesi Kapağı",
    "image": "images/urunler/bosch-deterjan-haznesi-kapagi.avif",
    "price": 1139,
    "oldPrice": 1389,
    "stock": 3
  },
  {
    "id": 137,
    "sku": "YP-10408",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Sepet Rayı Seti",
    "image": "images/urunler/siemens-sepet-rayi-seti.avif",
    "price": 1889,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 138,
    "sku": "YP-10411",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Tuz Haznesi Kapağı",
    "image": "images/urunler/vestel-tuz-haznesi-kapagi.avif",
    "price": 659,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 139,
    "sku": "YP-10414",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Pompa Motoru",
    "image": "images/urunler/beko-pompa-motoru.avif",
    "price": 1419,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 140,
    "sku": "YP-10417",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Parlatıcı Haznesi",
    "image": "images/urunler/arcelik-parlatici-haznesi.avif",
    "price": 189,
    "oldPrice": 229,
    "stock": 23
  },
  {
    "id": 141,
    "sku": "YP-10420",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Isıtıcı Rezistans",
    "image": "images/urunler/profilo-isitici-rezistans.avif",
    "price": 949,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 142,
    "sku": "YP-10423",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Yıkama Kolu",
    "image": "images/urunler/bosch-yikama-kolu.avif",
    "price": 1709,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 143,
    "sku": "YP-10426",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Kapı Lastiği",
    "price": 479,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 144,
    "sku": "YP-10429",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Kapı Kilidi Mekanizması",
    "image": "images/urunler/vestel-kapi-kilidi-mekanizmasi.avif",
    "price": 1239,
    "oldPrice": 1509,
    "stock": 3
  },
  {
    "id": 145,
    "sku": "YP-10432",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Su Alma Valfi",
    "image": "images/urunler/beko-su-alma-valfi.avif",
    "price": 1999,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 146,
    "sku": "YP-10435",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Termostat",
    "price": 769,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 147,
    "sku": "YP-10438",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Filtre Seti",
    "image": "images/urunler/profilo-filtre-seti.avif",
    "price": 1529,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 148,
    "sku": "YP-10441",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Sıcaklık Sensörü",
    "image": "images/urunler/bosch-sicaklik-sensoru.avif",
    "price": 289,
    "oldPrice": 349,
    "stock": 23
  },
  {
    "id": 149,
    "sku": "YP-10444",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Elektronik Kart",
    "image": "images/urunler/siemens-elektronik-kart.avif",
    "price": 1049,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 150,
    "sku": "YP-10447",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Deterjan Haznesi Kapağı",
    "image": "images/urunler/vestel-deterjan-haznesi-kapagi.avif",
    "price": 1809,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 151,
    "sku": "YP-10450",
    "category": "bulasik-makinesi",
    "categoryName": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Sepet Rayı Seti",
    "image": "images/urunler/beko-sepet-rayi-seti.avif",
    "price": 579,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 152,
    "sku": "YP-10453",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Sebzelik Rafı",
    "image": "images/urunler/beko-sebzelik-rafi.avif",
    "price": 559,
    "oldPrice": 679,
    "stock": 3
  },
  {
    "id": 153,
    "sku": "YP-10456",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Fan Motoru",
    "image": "images/urunler/vestel-fan-motoru.avif",
    "price": 1719,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 154,
    "sku": "YP-10459",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Buz Çözücü Rezistans",
    "image": "images/urunler/siemens-buz-cozucu-rezistans.avif",
    "price": 2889,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 155,
    "sku": "YP-10462",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "LG",
    "name": "LG Kompresör",
    "image": "images/urunler/lg-kompresor.avif",
    "price": 999,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 156,
    "sku": "YP-10465",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Işık Lambası Duyu",
    "image": "images/urunler/bosch-isik-lambasi-duyu.avif",
    "price": 2159,
    "oldPrice": 2629,
    "stock": 23
  },
  {
    "id": 157,
    "sku": "YP-10468",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Su Filtresi",
    "image": "images/urunler/arcelik-su-filtresi.avif",
    "price": 279,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 158,
    "sku": "YP-10471",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Samsung",
    "name": "Samsung Dijital Kontrol Kartı",
    "price": 1439,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 159,
    "sku": "YP-10474",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko No-Frost Sensörü",
    "image": "images/urunler/beko-no-frost-sensoru.avif",
    "price": 2599,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 160,
    "sku": "YP-10477",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Kapı Menteşesi",
    "image": "images/urunler/vestel-kapi-mentesesi.avif",
    "price": 719,
    "oldPrice": 879,
    "stock": 3
  },
  {
    "id": 161,
    "sku": "YP-10480",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Kompresör Rölesi",
    "image": "images/urunler/siemens-kompresor-rolesi.avif",
    "price": 1879,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 162,
    "sku": "YP-10483",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "LG",
    "name": "LG Kapı Contası",
    "image": "images/urunler/lg-kapi-contasi.avif",
    "price": 3039,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 163,
    "sku": "YP-10486",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Termostat",
    "image": "images/urunler/bosch-termostat.avif",
    "price": 1159,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 164,
    "sku": "YP-10489",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Kapak Contası Seti",
    "image": "images/urunler/arcelik-kapak-contasi-seti.avif",
    "price": 2319,
    "oldPrice": 2829,
    "stock": 23
  },
  {
    "id": 165,
    "sku": "YP-10492",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Samsung",
    "name": "Samsung Buz Kalıbı",
    "image": "images/urunler/samsung-buz-kalibi.avif",
    "price": 429,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 166,
    "sku": "YP-10495",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Sebzelik Rafı",
    "image": "images/urunler/beko-sebzelik-rafi-2.avif",
    "price": 1599,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 167,
    "sku": "YP-10498",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Fan Motoru",
    "image": "images/urunler/vestel-fan-motoru-2.avif",
    "price": 2759,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 168,
    "sku": "YP-10501",
    "category": "buzdolabi",
    "categoryName": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Buz Çözücü Rezistans",
    "image": "images/urunler/siemens-buz-cozucu-rezistans-2.avif",
    "price": 869,
    "oldPrice": 1059,
    "stock": 3
  },
  {
    "id": 169,
    "sku": "YP-10504",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Ocak Ateşleme Modülü",
    "image": "images/urunler/vestel-ocak-atesleme-modulu.avif",
    "price": 289,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 170,
    "sku": "YP-10507",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Fırın Termostatı",
    "image": "images/urunler/siemens-firin-termostati.avif",
    "price": 869,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 171,
    "sku": "YP-10510",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Ocak Brülör Başlığı",
    "image": "images/urunler/bosch-ocak-brulor-basligi.avif",
    "price": 1439,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 172,
    "sku": "YP-10513",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Izgara Motoru",
    "image": "images/urunler/arcelik-izgara-motoru.avif",
    "price": 509,
    "oldPrice": 619,
    "stock": 23
  },
  {
    "id": 173,
    "sku": "YP-10516",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Fırın Kapı Menteşesi",
    "image": "images/urunler/beko-firin-kapi-mentesesi.avif",
    "price": 1089,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 174,
    "sku": "YP-10519",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Ocak Gaz Musluğu",
    "image": "images/urunler/profilo-ocak-gaz-muslugu.avif",
    "price": 149,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 175,
    "sku": "YP-10522",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Fırın Fanı",
    "image": "images/urunler/vestel-firin-fani.avif",
    "price": 729,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 176,
    "sku": "YP-10525",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Fırın Rezistansı",
    "image": "images/urunler/siemens-firin-rezistansi.avif",
    "price": 1299,
    "oldPrice": 1579,
    "stock": 3
  },
  {
    "id": 177,
    "sku": "YP-10528",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Fırın Camı",
    "image": "images/urunler/bosch-firin-cami.avif",
    "price": 369,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 178,
    "sku": "YP-10531",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Zaman Ayar Saati",
    "image": "images/urunler/arcelik-zaman-ayar-saati.avif",
    "price": 949,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 179,
    "sku": "YP-10534",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Beko",
    "name": "Beko Ocak Pilot Ateşleyici",
    "image": "images/urunler/beko-ocak-pilot-atesleyici.avif",
    "price": 1519,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 180,
    "sku": "YP-10537",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Profilo",
    "name": "Profilo Fırın Lambası",
    "image": "images/urunler/profilo-firin-lambasi.avif",
    "price": 589,
    "oldPrice": 719,
    "stock": 23
  },
  {
    "id": 181,
    "sku": "YP-10540",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Ocak Ateşleme Modülü",
    "price": 1159,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 182,
    "sku": "YP-10543",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Siemens",
    "name": "Siemens Fırın Termostatı",
    "price": 229,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 183,
    "sku": "YP-10546",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Ocak Brülör Başlığı",
    "image": "images/urunler/bosch-ocak-brulor-basligi-2.avif",
    "price": 809,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 184,
    "sku": "YP-10549",
    "category": "firin-ocak",
    "categoryName": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Izgara Motoru",
    "image": "images/urunler/arcelik-izgara-motoru-2.avif",
    "price": 1379,
    "oldPrice": 1679,
    "stock": 3
  },
  {
    "id": 185,
    "sku": "YP-10552",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vaillant",
    "name": "Vaillant Klima Fan Motoru",
    "image": "images/urunler/vaillant-klima-fan-motoru.avif",
    "price": 679,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 186,
    "sku": "YP-10555",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Klima Uzaktan Kumanda",
    "image": "images/urunler/arcelik-klima-uzaktan-kumanda.avif",
    "price": 2059,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 187,
    "sku": "YP-10558",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Baymak",
    "name": "Baymak Klima Elektronik Kart",
    "image": "images/urunler/baymak-klima-elektronik-kart.avif",
    "price": 3429,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 188,
    "sku": "YP-10561",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Kombi Gaz Valfi",
    "image": "images/urunler/bosch-kombi-gaz-valfi.avif",
    "price": 1199,
    "oldPrice": 1459,
    "stock": 23
  },
  {
    "id": 189,
    "sku": "YP-10564",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Kombi Sirkülasyon Pompası",
    "image": "images/urunler/vestel-kombi-sirkulasyon-pompasi.avif",
    "price": 2579,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 190,
    "sku": "YP-10567",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Demirdöküm",
    "name": "Demirdöküm Klima Filtre Seti",
    "image": "images/urunler/demirdokum-klima-filtre-seti.avif",
    "price": 349,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 191,
    "sku": "YP-10570",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Daikin",
    "name": "Daikin Kombi Iyonizasyon Elektrodu",
    "image": "images/urunler/daikin-kombi-iyonizasyon-elektrodu.avif",
    "price": 1719,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 192,
    "sku": "YP-10573",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vaillant",
    "name": "Vaillant Klima Kompresörü",
    "image": "images/urunler/vaillant-klima-kompresoru.avif",
    "price": 3089,
    "oldPrice": 3769,
    "stock": 3
  },
  {
    "id": 193,
    "sku": "YP-10576",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Kombi Fan Ünitesi",
    "image": "images/urunler/arcelik-kombi-fan-unitesi.avif",
    "price": 869,
    "oldPrice": null,
    "stock": 8
  },
  {
    "id": 194,
    "sku": "YP-10579",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Baymak",
    "name": "Baymak Kombi Eşanjörü",
    "image": "images/urunler/baymak-kombi-esanjoru.avif",
    "price": 2239,
    "oldPrice": null,
    "stock": 13
  },
  {
    "id": 195,
    "sku": "YP-10582",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Bosch",
    "name": "Bosch Kombi Genleşme Tankı",
    "image": "images/urunler/bosch-kombi-genlesme-tanki.avif",
    "price": 3609,
    "oldPrice": null,
    "stock": 18
  },
  {
    "id": 196,
    "sku": "YP-10585",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vestel",
    "name": "Vestel Kombi Basınç Şalteri",
    "image": "images/urunler/vestel-kombi-basinc-salteri.avif",
    "price": 1389,
    "oldPrice": 1689,
    "stock": 23
  },
  {
    "id": 197,
    "sku": "YP-10588",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Demirdöküm",
    "name": "Demirdöküm Klima Fan Motoru",
    "image": "images/urunler/demirdokum-klima-fan-motoru.avif",
    "price": 2759,
    "oldPrice": null,
    "stock": 28
  },
  {
    "id": 198,
    "sku": "YP-10591",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Daikin",
    "name": "Daikin Klima Uzaktan Kumanda",
    "image": "images/urunler/daikin-klima-uzaktan-kumanda.avif",
    "price": 529,
    "oldPrice": null,
    "stock": 33
  },
  {
    "id": 199,
    "sku": "YP-10594",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Vaillant",
    "name": "Vaillant Klima Elektronik Kart",
    "image": "images/urunler/vaillant-klima-elektronik-kart.avif",
    "price": 1909,
    "oldPrice": null,
    "stock": 38
  },
  {
    "id": 200,
    "sku": "YP-10597",
    "category": "klima-kombi",
    "categoryName": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "brand": "Arçelik",
    "name": "Arçelik Kombi Gaz Valfi",
    "image": "images/urunler/arcelik-kombi-gaz-valfi.avif",
    "price": 3279,
    "oldPrice": 3999,
    "stock": 3
  }
];

const CATEGORIES = [
  {
    "slug": "camasir-makinesi",
    "name": "Çamaşır Makinesi Parçaları",
    "group": "beyaz-esya",
    "count": 17
  },
  {
    "slug": "bulasik-makinesi",
    "name": "Bulaşık Makinesi Parçaları",
    "group": "beyaz-esya",
    "count": 17
  },
  {
    "slug": "buzdolabi",
    "name": "Buzdolabı Parçaları",
    "group": "beyaz-esya",
    "count": 17
  },
  {
    "slug": "firin-ocak",
    "name": "Fırın & Ocak Parçaları",
    "group": "beyaz-esya",
    "count": 16
  },
  {
    "slug": "klima-kombi",
    "name": "Klima & Kombi Parçaları",
    "group": "beyaz-esya",
    "count": 16
  }
];
